Portfolio setup
zairdon20/JOSPHATS-FIRST pull request #1
Opened 2021-11-24 21:25 UTC by zairdon20

# Project Setup

### In the following milestone, I have:

- Made sure that there are no linter errors:

- Made sure that linters are set up correctly for this repository.

- Made sure that linter results are green.

- Made sure there are no custom changes to linter config.

- Made sure that I used the correct GitHub Flow:

- Made sure the README file is descriptive.

2021-11-24 22:32 UTC, Gambit142 requested changes
## Hi @zairdon20 👋, 

Good job so far!

## To Highlight
- Good pull request description ✔️ 
- Good start setting up the README.md (although it can be improved)
- Correct use of Github flow ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 22:32 UTC, Gambit142 commented on README.md
>  Additional description about the project and its features.
- [ ] I would like to suggest that you fix the broken image for the screenshot of this project. This is the way it looks presently. Kindly fix this

![image](https://user-images.githubusercontent.com/77106962/143317835-5cb8d7fc-4c20-4747-830e-6818454cc851.png)

2021-11-24 22:32 UTC, Gambit142 commented on index.html
> +        <h2>welcome</h2>
- [ ] Nice job implementing this, Kindly put the _**welcome text**_ in an `a` tag. The welcome text serves as the logo for the project. Ideally, the logo of any project should be clickable and should link to the homepage of a website. You can also make the `W` in the `welcome` to be in uppercase Kindly fix this. 🙏

2021-11-24 22:32 UTC, Gambit142 commented on style.css
> +}
- [ ] One of the project requirements is that you use flexbox to style the header and section in this portfolio. Kindly implement this specific project requirement for the section tag in your headline.

2021-11-24 22:32 UTC, Gambit142 commented on index.html
> +    </section>
- [ ] I would like to suggest that you work on the background images for the section part. One of the project requirements states that it should be the same as that of Figma's template. 

### Your portfolio
![image](https://user-images.githubusercontent.com/77106962/143319793-07d749bc-d6ef-4e4f-810f-b7601c465b80.png)

### Figma's Template
![image](https://user-images.githubusercontent.com/77106962/143320006-89b7285d-27fb-4bb5-b98f-3f76e1f04781.png)

Kindly work on this.

2021-11-24 22:32 UTC, Gambit142 commented on style.css
> +}
- [ ] Kindly make the icons the same size as that of Figma's template. You could make the size of the icon either `20px` or `1.25rem`

2021-11-25 11:42 UTC, VanessaAoki approved these changes
## STATUS: APPROVED 🟢 
Hi @zairdon20, 

Great job implementing all the changes required by the previous Code Reviewer, your project is complete! There is nothing else to say other than... it's time to merge it! 
Congratulations! 🎉 

<img alt="approved" src="https://64.media.tumblr.com/87e0b6469c957bf896cdec1cab646acf/tumblr_inline_pk1bdakCCp1rpcr9a_500.gif">

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 12:16 UTC, merged